### PR TITLE
Adding Mapping for the ChampionMastery endpoint

### PR DESCRIPTION
**Pull request by jkerak**
Added new ChampionMastery data transfer object, the methods to form
url's for the ChampionMaster endpoint, and supporting unit tests.

### CODE REVIEW

**Comment by jkerak** [comment]
Wanted to get this in time for the current API developer challenge, which ends May 9

**Comment by sdesyllas** [comment]
Thanks! Will merge your PR and release a new version on nuget ASAP.

**Comment by jkerak** [comment]
great... first time ever doing a pull request, hope it looks good.

**Comment by sdesyllas** [comment]
Yes it looks good, thanks for your contribution.
Cheers!

**Pull request merged**
